USERNAME = "admin"
PASSWORD = "admin"
SECRET_KEY = "clamNET"
MAINDIR = "/tmp/clamnet"
UPLOADDIR = "/tmp/clamnet/uploads"
LOCAL_INSTALL_FILE = "clamav-1.4.3.win.x64.msi"
REMOTE_INSTALL_FILE = "C:\\Windows\\Temp\\clamav-installer.msi"
LOCAL_CVD_FILE = "daily.cvd"